### ISSUE TITLE
ERROR in static/js/app.js from UglifyJs RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by feitianlee** [baidu/NoahV#139]
运行环境
NoahV :1.0.12
电脑Mac :10.14.4
node :v12.9.1

通过命令创建一个新的noahv项目。编译运行正常。但是通过sh build.sh打包提示
ERROR in static/js/app.js from UglifyJs
RangeError: Maximum call stack size exceeded
    at AST_Call.eval [as _eval] (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:1:1)
    at AST_Call.eval [as evaluate] (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:8714:28)
    at TreeWalker.eval [as callback] (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:9043:62)
    at TreeWalker.visit (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:1439:25)
    at AST_Return.walk (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:816:17)
    at eval (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:503:14)
    at Array.forEach (<anonymous>)
    at walk_body (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:502:15)
    at eval (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:515:13)
    at TreeWalker.visit (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:1440:31)
    at AST_BlockStatement.walk (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:514:17)
    at eval (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:874:23)
    at TreeWalker.visit (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:1440:31)
    at AST_If.walk (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:872:17)
    at eval (eval at <anonymous> (/Users/apple/Documents/project/noahvtest/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:503:14)
    at Array.forEach (<anonymous>)

**Comment by darrenywyu** [comment]
如出现上述现象，可尝试打开项目根目录下的`package.json`文件，将 `uglifyjs-webpack-plugin`的版本号修改为 "2.1.2"。
